### ISSUE TITLE
How to Fix this error

### ISSUE THREAD

**Issue by NieahWieah** [DeBullVader/BU_Blender_AssetLibrary_Plugin#2]
When trying to add a AssetLibrary folder I get this error message which won't allow me to continue on to download the Asset Library

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\offic\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Baked_Blender_Suite\operators\add_lib_path.py", line 15, in execute
    dir_path = add_core_library()
  File "C:\Users\offic\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Baked_Blender_Suite\utils\addon_info.py", line 89, in add_core_library
    bpy.ops.preferences.asset_library_add(directory = dir_path, check_existing = True)
  File "C:\Users\offic\Desktop\blender-3.0.0-windows-x64\blender-3.0.0-windows-x64\3.0\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "check_existing" unrecognized

location: <unknown location>:-1

**Comment by DeBullVader** [comment]
It seems you are running blender 3.0 the minimum requirement is 3.5 for this add-on.
