### ISSUE TITLE
Cannot download by any version blender

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [DeBullVader/BU_Blender_AssetLibrary_Plugin#4]
It failed

```
Exception in thread Thread-45 (check_for_new_assets):
Traceback (most recent call last):
  File "G:\blender\36\3.6\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "G:\blender\36\3.6\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "G:\blenderplus\3.0\addons\Baked_Blender_Suite\operators\library_download.py", line 365, in check_for_new_assets
    assets = get_asset_list().items()
  File "G:\blenderplus\3.0\addons\Baked_Blender_Suite\operators\library_download.py", line 61, in get_asset_list
    result = request.execute()
  File "G:\blenderplus\3.0\addons\Baked_Blender_Suite\dependencies/windows\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "G:\blenderplus\3.0\addons\Baked_Blender_Suite\dependencies/windows\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "G:\blenderplus\3.0\addons\Baked_Blender_Suite\dependencies/windows\googleapiclient\http.py", line 222, in _retry_request
    raise exception
  File "G:\blenderplus\3.0\addons\Baked_Blender_Suite\dependencies/windows\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "G:\blenderplus\3.0\addons\Baked_Blender_Suite\dependencies/windows\oauth2client\transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "G:\blenderplus\3.0\addons\Baked_Blender_Suite\dependencies/windows\oauth2client\client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "G:\blenderplus\3.0\addons\Baked_Blender_Suite\dependencies/windows\oauth2client\client.py", line 778, in _do_refresh_request
    resp, content = transport.request(
  File "G:\blenderplus\3.0\addons\Baked_Blender_Suite\dependencies/windows\oauth2client\transport.py", line 280, in request
    return http_callable(uri, method=method, body=body, headers=headers,
  File "G:\blenderplus\3.0\addons\Baked_Blender_Suite\dependencies/windows\httplib2\__init__.py", line 1724, in request
    (response, content) = self._request(
  File "G:\blenderplus\3.0\addons\Baked_Blender_Suite\dependencies/windows\httplib2\__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "G:\blenderplus\3.0\addons\Baked_Blender_Suite\dependencies/windows\httplib2\__init__.py", line 1366, in _conn_request
    conn.connect()
  File "G:\blenderplus\3.0\addons\Baked_Blender_Suite\dependencies/windows\httplib2\__init__.py", line 1156, in connect
    sock.connect((self.host, self.port))
TimeoutError: [WinError 10060]
```

Could you Update asset files on github or gumroad individually？（Like update it every 3 day）
Help the user who can‘t download it as normal as me.

**Comment by DeBullVader** [comment]
What version of blender are you using. minimum requirment is 3.5 
3.6 has noot been tested yet. The above error shows two version? 3.6 and 3.0

**Comment by BUGProtectionAssociation** [comment]
> What version of blender are you using. minimum requirment is 3.5 3.6 has noot been tested yet. The above error shows two version? 3.6 and 3.0

3.5 and 3.6

**Comment by DeBullVader** [comment]
TimeoutError: [WinError 10060] is a connection issue between your pc and the server. It takes to long to respond to the request.  So the request gets timed out. 
Do you have a vpn running or something similar? It can also be a  firewall issue.

**Comment by DeBullVader** [comment]
It might be easier to join our discord and see if we can find a solution. https://discord.gg/bakeduniverse
